KinesisConsumer: Fix FloggerFormatString pattern flagged by error prone
  KinesisConsumer.java:86: error: [FloggerFormatString]
  missing argument for format specifier '%s'
    logger.atInfo().log("Waiting up to %s seconds for shutdown to complete.");
                       ^
    (see https://errorprone.info/bugpattern/FloggerFormatString)

Change-Id: I2483d709e72ac19c505c7508d85c1fab9afa1764